"""
train.py
========
Training loop for the FisherCNN model.

Usage
-----
    python train.py                          # train with defaults
    python train.py --n_samples 10000        # quick test run
    python train.py --dataset dataset.h5     # use pre-built dataset

Features
--------
  - Auto-detects MPS (Apple M1), CUDA, or CPU
  - Multi-task loss: λ_F · MSE_Fourier + λ_A · MSE_AF + λ_C · consistency
  - Cosine LR schedule + early stopping
  - Checkpoints best model by validation loss
  - Saves training curves and evaluation plots
"""

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
import h5py
from tqdm import tqdm
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

from model import FisherCNN
from dataset import generate_dataset


# ─────────────────────────────────────────────────────────────────────────────
# Device selection — M1 Mac uses MPS
# ─────────────────────────────────────────────────────────────────────────────

def get_device() -> torch.device:
    if torch.backends.mps.is_available():
        print("Using Apple MPS (M1 GPU)")
        return torch.device('mps')
    elif torch.cuda.is_available():
        print(f"Using CUDA: {torch.cuda.get_device_name(0)}")
        return torch.device('cuda')
    else:
        print("Using CPU")
        return torch.device('cpu')


# ─────────────────────────────────────────────────────────────────────────────
# Dataset wrapper
# ─────────────────────────────────────────────────────────────────────────────

class FisherDataset(Dataset):
    """Loads the HDF5 dataset generated by dataset.py"""

    def __init__(self, h5_path: str):
        self.h5_path = h5_path
        with h5py.File(h5_path, 'r') as f:
            self.n = f['images'].shape[0]
            # load everything into RAM for fast M1 access
            self.images      = torch.tensor(f['images'][:],      dtype=torch.float32)
            self.cos_coeffs  = torch.tensor(f['cos_coeffs'][:],  dtype=torch.float32)
            self.sin_coeffs  = torch.tensor(f['sin_coeffs'][:],  dtype=torch.float32)
            self.AF          = torch.tensor(f['AF'][:],           dtype=torch.float32)
            self.descriptors = torch.tensor(f['descriptor'][:],   dtype=torch.float32)
            self.geom_ids    = torch.tensor(f['geometry_id'][:],  dtype=torch.long)
            self.snr_db      = torch.tensor(f['snr_db'][:],       dtype=torch.float32)
            self.sigma_b     = torch.tensor(f['sigma_b'][:],      dtype=torch.float32)

    def __len__(self):
        return self.n

    def __getitem__(self, idx):
        return {
            'image':      self.images[idx],
            'descriptor': self.descriptors[idx],
            'cos':        self.cos_coeffs[idx],
            'sin':        self.sin_coeffs[idx],
            'AF':         self.AF[idx],
            'geom_id':    self.geom_ids[idx],
            'snr_db':     self.snr_db[idx],
            'sigma_b':    self.sigma_b[idx],
        }


# ─────────────────────────────────────────────────────────────────────────────
# Loss function
# ─────────────────────────────────────────────────────────────────────────────

class FisherLoss(nn.Module):
    """
    L = λ_F · MSE(Fourier) + λ_A · MSE(A_F) + λ_C · L_consistency

    Consistency loss: penalises disagreement between predictions on
    the original and a randomly rotated version of the same image.
    (Simplified here as L2 between two forward passes with different
    augmentation seeds — full group-equivariant version can be added.)

    [Karniadakis et al. 2021]
    """
    def __init__(self, lambda_F: float = 1.0,
                        lambda_A: float = 0.5,
                        lambda_C: float = 0.1):
        super().__init__()
        self.lambda_F = lambda_F
        self.lambda_A = lambda_A
        self.lambda_C = lambda_C
        self.mse      = nn.MSELoss()

    def forward(self, cos_pred, sin_pred, AF_pred,
                cos_true, sin_true, AF_true,
                cos_pred2=None, sin_pred2=None):
        """
        Parameters
        ----------
        cos_pred, sin_pred : (B, M)  predicted Fourier coefficients
        AF_pred            : (B, 1)  predicted anisotropy index
        cos_true, sin_true : (B, M)  ground truth
        AF_true            : (B,)    ground truth
        cos_pred2, sin_pred2 : optional second pass for consistency
        """
        L_fourier = self.mse(cos_pred, cos_true) + \
                    self.mse(sin_pred, sin_true)
        # Scale A_F loss: true A_F ∈ [0,1] but Fourier coeffs can be O(1).
        # Normalise both to unit variance so neither dominates.
        L_AF      = self.mse(AF_pred.squeeze(), AF_true)

        L_cons = torch.tensor(0.0, device=cos_pred.device)
        if cos_pred2 is not None:
            L_cons = self.mse(cos_pred, cos_pred2) + \
                     self.mse(sin_pred, sin_pred2)

        total = (self.lambda_F * L_fourier +
                 self.lambda_A * L_AF +
                 self.lambda_C * L_cons)
        return total, L_fourier.item(), L_AF.item(), L_cons.item()


# ─────────────────────────────────────────────────────────────────────────────
# Training utilities
# ─────────────────────────────────────────────────────────────────────────────

def rotate_images_90(images: torch.Tensor) -> torch.Tensor:
    """Rotate batch of images by 90° for consistency regularisation."""
    return torch.rot90(images, k=1, dims=[2, 3])


def compute_metrics(model, loader, device, criterion):
    """Full evaluation on a DataLoader. Returns dict of metrics."""
    model.eval()
    all_AF_pred, all_AF_true = [], []
    all_cos_pred, all_cos_true = [], []
    total_loss = 0.0
    n_batches  = 0

    with torch.no_grad():
        for batch in loader:
            img  = batch['image'].to(device)
            desc = batch['descriptor'].to(device)
            cos_t = batch['cos'].to(device)
            sin_t = batch['sin'].to(device)
            AF_t  = batch['AF'].to(device)

            cos_p, sin_p, AF_p = model(img, desc)
            loss, _, _, _ = criterion(cos_p, sin_p, AF_p, cos_t, sin_t, AF_t)

            total_loss += loss.item()
            n_batches  += 1

            all_AF_pred.extend(AF_p.squeeze().cpu().numpy())
            all_AF_true.extend(AF_t.cpu().numpy())
            all_cos_pred.append(cos_p.cpu().numpy())
            all_cos_true.append(cos_t.cpu().numpy())

    all_AF_pred = np.array(all_AF_pred)
    all_AF_true = np.array(all_AF_true)
    all_cos_pred = np.vstack(all_cos_pred)
    all_cos_true = np.vstack(all_cos_true)

    # MSE over Fourier coefficients
    mse_fourier = float(np.mean((all_cos_pred - all_cos_true)**2))
    # Pearson r for A_F
    pearson_r = float(np.corrcoef(all_AF_pred, all_AF_true)[0, 1])
    # MAE for A_F
    mae_AF = float(np.mean(np.abs(all_AF_pred - all_AF_true)))

    return {
        'loss':        total_loss / max(n_batches, 1),
        'mse_fourier': mse_fourier,
        'pearson_r':   pearson_r,
        'mae_AF':      mae_AF,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Plots
# ─────────────────────────────────────────────────────────────────────────────

def plot_training_curves(history: dict, out_dir: Path):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    axes[0].plot(history['train_loss'], label='Train')
    axes[0].plot(history['val_loss'],   label='Val')
    axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Total Loss')
    axes[0].set_title('Loss'); axes[0].legend(); axes[0].set_yscale('log')

    axes[1].plot(history['val_mse_fourier'])
    axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('MSE')
    axes[1].set_title('Fourier Coefficient MSE (val)')

    axes[2].plot(history['val_pearson_r'])
    axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('r')
    axes[2].set_title('Pearson r — Anisotropy Index (val)')
    axes[2].set_ylim(0, 1)

    plt.tight_layout()
    plt.savefig(out_dir / 'training_curves.png', dpi=150)
    plt.close()
    print(f"Saved training curves → {out_dir / 'training_curves.png'}")


def plot_parity(model, loader, device, out_dir: Path, n_points: int = 500):
    """Scatter plot of predicted vs true A_F."""
    model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for batch in loader:
            if len(preds) >= n_points:
                break
            img  = batch['image'].to(device)
            desc = batch['descriptor'].to(device)
            AF_t = batch['AF'].numpy()
            _, _, AF_p = model(img, desc)
            preds.extend(AF_p.squeeze().cpu().numpy())
            trues.extend(AF_t)

    preds = np.array(preds[:n_points])
    trues = np.array(trues[:n_points])
    r2 = r2_score(trues, preds)

    fig, ax = plt.subplots(figsize=(5, 5))
    ax.scatter(trues, preds, s=8, alpha=0.4, c='steelblue')
    lo, hi = min(trues.min(), preds.min()), max(trues.max(), preds.max())
    ax.plot([lo, hi], [lo, hi], 'r--', lw=1.5, label='ideal')
    ax.set_xlabel('True $A_F$'); ax.set_ylabel('Predicted $A_F$')
    ax.set_title(f'Anisotropy Index Parity  ($R^2={r2:.3f}$)')
    ax.legend()
    plt.tight_layout()
    plt.savefig(out_dir / 'parity_AF.png', dpi=150)
    plt.close()
    print(f"Saved parity plot → {out_dir / 'parity_AF.png'}")


# ─────────────────────────────────────────────────────────────────────────────
# Main training function
# ─────────────────────────────────────────────────────────────────────────────

def train(args):
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    device  = get_device()

    # ── Build / load dataset ─────────────────────────────────────────────────
    ds_path = Path(args.dataset)
    if not ds_path.exists():
        print(f"Dataset not found at {ds_path}. Generating {args.n_samples} samples …")
        generate_dataset(
            n_samples=args.n_samples,
            grid_size=args.grid_size,
            output_path=str(ds_path),
            verbose=True,
        )

    print(f"Loading dataset from {ds_path} …")
    full_ds = FisherDataset(str(ds_path))
    print(f"  Total samples: {len(full_ds)}")

    # 80/10/10 split
    n_total = len(full_ds)
    n_val   = int(0.10 * n_total)
    n_test  = int(0.10 * n_total)
    n_train = n_total - n_val - n_test

    train_ds, val_ds, test_ds = random_split(
        full_ds, [n_train, n_val, n_test],
        generator=torch.Generator().manual_seed(42)
    )
    print(f"  Train: {len(train_ds)}  Val: {len(val_ds)}  Test: {len(test_ds)}")

    train_loader = DataLoader(train_ds, batch_size=args.batch_size,
                              shuffle=True,  num_workers=0, pin_memory=False)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch_size,
                              shuffle=False, num_workers=0, pin_memory=False)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch_size,
                              shuffle=False, num_workers=0, pin_memory=False)

    # ── Model ────────────────────────────────────────────────────────────────
    descriptor_dim = full_ds.descriptors.shape[1]  # 2K+1 = 7
    model = FisherCNN(
        grid_size=args.grid_size,
        descriptor_dim=descriptor_dim,
        M=args.M,
        dropout_rate=args.dropout,
    ).to(device)
    print(f"Model parameters: {model.count_parameters():,}")

    # ── Loss & optimizer ─────────────────────────────────────────────────────
    criterion = FisherLoss(
        lambda_F=args.lambda_F,
        lambda_A=args.lambda_A,
        lambda_C=args.lambda_C,
    )
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6
    )

    # ── Training loop ────────────────────────────────────────────────────────
    history = {k: [] for k in
               ['train_loss','val_loss','val_mse_fourier','val_pearson_r','val_mae_AF']}
    best_val_loss = float('inf')
    patience_count = 0
    ckpt_path = out_dir / 'best_model.pt'

    print(f"\nTraining for up to {args.epochs} epochs (early stop patience={args.patience})\n")
    t0 = time.time()

    for epoch in range(1, args.epochs + 1):
        # ── Train ────────────────────────────────────────────────────────────
        model.train()
        epoch_loss = 0.0
        pbar = tqdm(train_loader,
                    desc=f"Epoch {epoch:3d}/{args.epochs}",
                    leave=False)

        for batch in pbar:
            img  = batch['image'].to(device)
            desc = batch['descriptor'].to(device)
            cos_t = batch['cos'].to(device)
            sin_t = batch['sin'].to(device)
            AF_t  = batch['AF'].to(device)

            optimizer.zero_grad()
            cos_p, sin_p, AF_p = model(img, desc)

            # consistency pass: rotate images by 90°
            img_rot   = rotate_images_90(img)
            cos_p2, sin_p2, _ = model(img_rot, desc)

            loss, lf, la, lc = criterion(
                cos_p, sin_p, AF_p,
                cos_t, sin_t, AF_t,
                cos_p2, sin_p2
            )
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            pbar.set_postfix({'loss': f'{loss.item():.4f}',
                              'Lf': f'{lf:.4f}',
                              'La': f'{la:.4f}'})

        scheduler.step()

        # ── Validate ──────────────────────────────────────────────────────
        val_metrics = compute_metrics(model, val_loader, device, criterion)

        history['train_loss'].append(epoch_loss / len(train_loader))
        history['val_loss'].append(val_metrics['loss'])
        history['val_mse_fourier'].append(val_metrics['mse_fourier'])
        history['val_pearson_r'].append(val_metrics['pearson_r'])
        history['val_mae_AF'].append(val_metrics['mae_AF'])

        lr_now = scheduler.get_last_lr()[0]
        print(f"Epoch {epoch:3d} | "
              f"train={history['train_loss'][-1]:.4f} | "
              f"val={val_metrics['loss']:.4f} | "
              f"MSE_F={val_metrics['mse_fourier']:.4e} | "
              f"r_AF={val_metrics['pearson_r']:.3f} | "
              f"LR={lr_now:.2e}")

        # ── Checkpoint ────────────────────────────────────────────────────
        if val_metrics['loss'] < best_val_loss:
            best_val_loss = val_metrics['loss']
            torch.save({
                'epoch':      epoch,
                'model_state': model.state_dict(),
                'optimizer':   optimizer.state_dict(),
                'val_metrics': val_metrics,
                'args':        vars(args),
            }, ckpt_path)
            patience_count = 0
        else:
            patience_count += 1
            if patience_count >= args.patience:
                print(f"\nEarly stopping at epoch {epoch} "
                      f"(no improvement for {args.patience} epochs).")
                break

    elapsed = time.time() - t0
    print(f"\nTraining complete in {elapsed/60:.1f} min.")

    # ── Final test evaluation ─────────────────────────────────────────────
    print("\nLoading best checkpoint for test evaluation …")
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt['model_state'])
    test_metrics = compute_metrics(model, test_loader, device, criterion)

    print("\n══════ TEST RESULTS ══════")
    print(f"  Loss           : {test_metrics['loss']:.4f}")
    print(f"  MSE (Fourier)  : {test_metrics['mse_fourier']:.4e}")
    print(f"  Pearson r (AF) : {test_metrics['pearson_r']:.4f}")
    print(f"  MAE   (AF)     : {test_metrics['mae_AF']:.4f}")
    print("══════════════════════════\n")

    # ── Save outputs ──────────────────────────────────────────────────────
    results = {
        'test_metrics':  test_metrics,
        'best_val_loss': best_val_loss,
        'n_params':      model.count_parameters(),
        'epochs_trained': len(history['train_loss']),
        'elapsed_min':   elapsed / 60,
    }
    with open(out_dir / 'results.json', 'w') as f:
        json.dump(results, f, indent=2)

    plot_training_curves(history, out_dir)
    plot_parity(model, test_loader, device, out_dir)

    print(f"All outputs saved to → {out_dir}/")
    return model, test_metrics


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description='Train FisherCNN on quantum dot dataset')

    # Dataset
    p.add_argument('--dataset',    default='dataset.h5',
                   help='Path to HDF5 dataset (generated if missing)')
    p.add_argument('--n_samples',  type=int, default=80_000,
                   help='Samples to generate if dataset missing')
    p.add_argument('--grid_size',  type=int, default=64)
    p.add_argument('--M',          type=int, default=6,
                   help='Number of Fourier modes to predict')

    # Model
    p.add_argument('--dropout',    type=float, default=0.1)

    # Loss weights  [Karniadakis et al. 2021]
    p.add_argument('--lambda_F',   type=float, default=1.0)
    p.add_argument('--lambda_A',   type=float, default=0.5)
    p.add_argument('--lambda_C',   type=float, default=0.1)

    # Training
    p.add_argument('--epochs',     type=int,   default=120)
    p.add_argument('--batch_size', type=int,   default=64)
    p.add_argument('--lr',         type=float, default=1e-3)
    p.add_argument('--patience',   type=int,   default=20,
                   help='Early stopping patience (epochs)')

    # Output
    p.add_argument('--out_dir',    default='outputs/',
                   help='Directory for checkpoints and plots')

    return p.parse_args()


if __name__ == '__main__':
    args = parse_args()
    train(args)
